import { IMember } from '../../interfaces';

export const MEMBERS: IMember[] = [
	{
		id: '1',
		first_name: 'Jorge',
		last_name: 'Marchant',
		second_surname: 'Brahm',
		position: '1.Vorsitzender',
	},
	{
		id: '2',
		first_name: 'Harry',
		last_name: 'Meyer',
		second_surname: 'Guerrero',
		position: '2.Vorsitzender',
	},
	{
		id: '3',
		first_name: 'Ignacio',
		last_name: 'Brintrup',
		second_surname: 'Bonvallet',
		position: 'Schriftwart',
	},
	{
		id: '4',
		first_name: 'Pablo ',
		last_name: 'Brahm',
		second_surname: 'Rosas',
		position: 'Kassenwart',
	},
	{
		id: '5',
		first_name: 'Jaime ',
		last_name: 'Marchant',
		second_surname: 'Brahm',
		position: 'Vorstandsmitglieder',
	},
	{
		id: '6',
		first_name: 'Alejandro',
		last_name: 'Wahl',
		second_surname: 'Böhme',
		position: 'Vorstandsmitglieder',
	},
	{
		id: '7',
		first_name: 'Enrique',
		last_name: 'Oyarzun ',
		second_surname: 'Scholtbach',
		position: 'Vorstandsmitglieder',
	},
	{
		id: '8',
		first_name: 'German ',
		last_name: 'Weitzler',
		second_surname: 'Zarges',
		position: 'Ehren Beisitzender',
	},
	{
		id: '9',
		first_name: 'Henry',
		last_name: 'Scholtbach  ',
		second_surname: 'Zarges',
		position: 'Ehren Mitglieder',
	},
	{
		id: '10',
		first_name: 'Rodolfo ',
		last_name: 'Stange',
		second_surname: 'Oelckers',
		position: 'Ehren Mitglieder',
	},
	{
		id: '11',
		first_name: 'Martin',
		last_name: 'Ercoreca',
		second_surname: 'von Bischoffshausen',
		position: 'Ehren Mitglieder',
	},
	{
		id: '12',
		first_name: 'Federico',
		last_name: 'Oelckers',
		second_surname: 'Sepulveda',
		position: 'Ehren Mitglieder',
	},
	{
		id: '13',
		first_name: 'Ruben ',
		last_name: 'Alvarado',
		second_surname: 'Figueroa',
		position: 'Mitglieder',
	},
	{
		id: '14',
		first_name: 'Daniela',
		last_name: 'Alvarado',
		second_surname: 'Hermosilla',
		position: 'Mitglieder',
	},
	{
		id: '15',
		first_name: 'Gerardo',
		last_name: 'Bartsch',
		second_surname: 'Lohrmann',
		position: 'Mitglieder',
	},
	{
		id: '16',
		first_name: 'Rudy',
		last_name: 'Bartsch',
		second_surname: 'Lohrmann',
		position: 'Mitglieder',
	},
	{
		id: '17',
		first_name: 'Katjia',
		last_name: 'Berndt',
		second_surname: 'Schuhmacher',
		position: 'Mitglieder',
	},
	{
		id: '18',
		first_name: 'Jose',
		last_name: 'Berndt',
		second_surname: 'Sole',
		position: 'Mitglieder',
	},
	{
		id: '19',
		first_name: 'Juan',
		last_name: 'Berndt',
		second_surname: 'Sole',
		position: 'Mitglieder',
	},
	{
		id: '20',
		first_name: 'Thomas',
		last_name: 'Berndt',
		second_surname: 'Sole',
		position: 'Mitglieder',
	},
	{
		id: '21',
		first_name: 'Jose',
		last_name: 'Brahm',
		second_surname: 'Navarrete',
		position: 'Mitglieder',
	},
	{
		id: '22',
		first_name: 'Ignacio',
		last_name: 'Brintrup',
		second_surname: 'Bonvallet',
		position: 'Mitglieder',
	},
	{
		id: '23',
		first_name: 'Jaime ',
		last_name: 'Brintrup',
		second_surname: 'Bonvallet',
		position: 'Mitglieder',
	},
	{
		id: '24',
		first_name: 'Lilian',
		last_name: 'Cardenas ',
		second_surname: 'Elgueta',
		position: 'Mitglieder',
	},
	{
		id: '25',
		first_name: 'Mauricio',
		last_name: 'Cardenas ',
		second_surname: 'Elgueta',
		position: 'Mitglieder',
	},
	{
		id: '26',
		first_name: 'Francisca ',
		last_name: 'Cardenas ',
		second_surname: 'Elgueta',
		position: 'Mitglieder',
	},
	{
		id: '27',
		first_name: 'Ignacio ',
		last_name: 'Cardenas ',
		second_surname: 'Elgueta',
		position: 'Mitglieder',
	},
	{
		id: '28',
		first_name: 'Mauricio',
		last_name: 'Cardenas ',
		second_surname: 'Garcia',
		position: 'Mitglieder',
	},
	{
		id: '29',
		first_name: 'Victor',
		last_name: 'Correa',
		second_surname: 'Bohle',
		position: 'Mitglieder',
	},
	{
		id: '30',
		first_name: 'Rolando',
		last_name: 'De Solminihac',
		second_surname: 'Oelckers',
		position: 'Mitglieder',
	},
	{
		id: '31',
		first_name: 'Jaime',
		last_name: 'Ercoreca',
		second_surname: 'Negron',
		position: 'Mitglieder',
	},
	{
		id: '32',
		first_name: 'Hans',
		last_name: 'Fiebig',
		second_surname: 'Müller',
		position: 'Mitglieder',
	},
	{
		id: '33',
		first_name: 'Eduardo',
		last_name: 'Frene',
		second_surname: 'Dietz',
		position: 'Mitglieder',
	},
	{
		id: '34',
		first_name: 'Gerardo',
		last_name: 'Fuchslocher',
		second_surname: 'Marquez',
		position: 'Mitglieder',
	},
	{
		id: '35',
		first_name: 'Rene ',
		last_name: 'Fuchslocher ',
		second_surname: 'Raddatz',
		position: 'Mitglieder',
	},
	{
		id: '36',
		first_name: 'Roberto',
		last_name: 'Gallardo',
		second_surname: 'Weitzler',
		position: 'Mitglieder',
	},
	{
		id: '37',
		first_name: 'Helga',
		last_name: 'Georg',
		second_surname: 'Frese',
		position: 'Mitglieder',
	},
	{
		id: '38',
		first_name: 'Roberto',
		last_name: 'Gordon ',
		second_surname: 'Agliati',
		position: 'Mitglieder',
	},
	{
		id: '39',
		first_name: 'Arturo',
		last_name: 'Guijon ',
		second_surname: 'Errazuriz',
		position: 'Mitglieder',
	},
	{
		id: '40',
		first_name: 'Sergio',
		last_name: 'Haeger',
		second_surname: 'Yunge',
		position: 'Mitglieder',
	},
	{
		id: '41',
		first_name: 'Adrian ',
		last_name: 'Hamman',
		second_surname: 'Henkes',
		position: 'Mitglieder',
	},
	{
		id: '42',
		first_name: 'Nikolas ',
		last_name: 'Heinz',
		second_surname: 'Davila',
		position: 'Mitglieder',
	},
	{
		id: '43',
		first_name: 'Byron',
		last_name: 'Herz',
		second_surname: 'Barria',
		position: 'Mitglieder',
	},
	{
		id: '44',
		first_name: 'Johann',
		last_name: 'Herz',
		second_surname: 'Barria',
		position: 'Mitglieder',
	},
	{
		id: '45',
		first_name: 'Thomas',
		last_name: 'Herz',
		second_surname: 'Klein',
		position: 'Mitglieder',
	},
	{
		id: '46',
		first_name: 'Ricardo',
		last_name: 'Hölck',
		second_surname: 'Kusch',
		position: 'Mitglieder',
	},
	{
		id: '47',
		first_name: 'Agustin',
		last_name: 'Hölck',
		second_surname: 'Alvarado',
		position: 'Mitglieder',
	},
	{
		id: '48',
		first_name: 'Erwin',
		last_name: 'Klein',
		second_surname: 'Neira',
		position: 'Mitglieder',
	},
	{
		id: '49',
		first_name: 'Juan',
		last_name: 'Klein',
		second_surname: 'Schmidt',
		position: 'Mitglieder',
	},
	{
		id: '50',
		first_name: 'Alejandro',
		last_name: 'Krebs',
		second_surname: 'Schwerter',
		position: 'Mitglieder',
	},
	{
		id: '51',
		first_name: 'Camila',
		last_name: 'Kusch',
		second_surname: 'De La Puente',
		position: 'Mitglieder',
	},
	{
		id: '52',
		first_name: 'Catalina',
		last_name: 'Kusch',
		second_surname: 'De La Puente',
		position: 'Mitglieder',
	},
	{
		id: '53',
		first_name: 'Heinz',
		last_name: 'Kusch',
		second_surname: 'De La Puente',
		position: 'Mitglieder',
	},
	{
		id: '54',
		first_name: 'Irene',
		last_name: 'Kusch',
		second_surname: 'Hechenleitner',
		position: 'Mitglieder',
	},
	{
		id: '55',
		first_name: 'Rolf',
		last_name: 'Kusch',
		second_surname: 'Rensinghoff',
		position: 'Mitglieder',
	},
	{
		id: '56',
		first_name: 'Pedro',
		last_name: 'Laporte',
		second_surname: 'Miguel',
		position: 'Mitglieder',
	},
	{
		id: '57',
		first_name: 'Norman',
		last_name: 'Lintz',
		second_surname: 'Stange',
		position: 'Mitglieder',
	},
	{
		id: '58',
		first_name: 'Christian',
		last_name: 'Loebel',
		second_surname: 'Arcos',
		position: 'Mitglieder',
	},
	{
		id: '59',
		first_name: 'Mario',
		last_name: 'Marchant',
		second_surname: 'Brahm',
		position: 'Mitglieder',
	},
	{
		id: '60',
		first_name: 'Joaquin',
		last_name: 'Marchant',
		second_surname: 'Diaz',
		position: 'Mitglieder',
	},
	{
		id: '61',
		first_name: 'Jorge',
		last_name: 'Marchant',
		second_surname: 'Diaz',
		position: 'Mitglieder',
	},
	{
		id: '62',
		first_name: 'Cristian',
		last_name: 'Marchant',
		second_surname: 'France',
		position: 'Mitglieder',
	},
	{
		id: '63',
		first_name: 'Alejandro',
		last_name: 'Marchant',
		second_surname: 'Hardessen',
		position: 'Mitglieder',
	},
	{
		id: '64',
		first_name: 'Hernan',
		last_name: 'Marchant',
		second_surname: 'Hardessen',
		position: 'Mitglieder',
	},
	{
		id: '65',
		first_name: 'Macarena',
		last_name: 'Marchant',
		second_surname: 'Martinez',
		position: 'Mitglieder',
	},
	{
		id: '66',
		first_name: 'Mario',
		last_name: 'Marchant',
		second_surname: 'Martinez',
		position: 'Mitglieder',
	},
	{
		id: '67',
		first_name: 'Alberto',
		last_name: 'Marchant',
		second_surname: 'Olbrich',
		position: 'Mitglieder',
	},
	{
		id: '68',
		first_name: 'Gaston',
		last_name: 'Marchant',
		second_surname: 'Roa',
		position: 'Mitglieder',
	},
	{
		id: '69',
		first_name: 'Rudy',
		last_name: 'Meyer',
		second_surname: 'Rosemberg',
		position: 'Mitglieder',
	},
	{
		id: '70',
		first_name: 'Rudy ',
		last_name: 'Meyer',
		second_surname: 'Ruiz',
		position: 'Mitglieder',
	},
	{
		id: '71',
		first_name: 'Alejandro',
		last_name: 'Meza',
		second_surname: 'Werner',
		position: 'Mitglieder',
	},
	{
		id: '72',
		first_name: 'Konrad',
		last_name: 'Möller-Holtkamp',
		second_surname: 'Kaiser',
		position: 'Mitglieder',
	},
	{
		id: '73',
		first_name: 'Rolf',
		last_name: 'Möller-Holtkamp',
		second_surname: 'Jaederlund',
		position: 'Mitglieder',
	},
	{
		id: '74',
		first_name: 'Sven',
		last_name: 'Möller-Holtkamp',
		second_surname: 'Jaederlund',
		position: 'Mitglieder',
	},
	{
		id: '75',
		first_name: 'Pablo',
		last_name: 'Moore',
		second_surname: 'Ross',
		position: 'Mitglieder',
	},
	{
		id: '76',
		first_name: 'Luis',
		last_name: 'Navarro',
		second_surname: 'Gonzalez',
		position: 'Mitglieder',
	},
	{
		id: '77',
		first_name: 'Juan',
		last_name: 'Navarro',
		second_surname: 'Gonzalez',
		position: 'Mitglieder',
	},
	{
		id: '78',
		first_name: 'Joaquin',
		last_name: 'Neumann',
		second_surname: 'Heisse',
		position: 'Mitglieder',
	},
	{
		id: '79',
		first_name: 'Guillermo',
		last_name: 'Neumann',
		second_surname: 'Perez',
		position: 'Mitglieder',
	},
	{
		id: '80',
		first_name: 'Jaime',
		last_name: 'Oelckers',
		second_surname: 'Stange',
		position: 'Mitglieder',
	},
	{
		id: '81',
		first_name: 'Ignacio',
		last_name: 'Oyarzun',
		second_surname: 'Aguilera',
		position: 'Mitglieder',
	},
	{
		id: '82',
		first_name: 'Eduardo ',
		last_name: 'Oyarzun',
		second_surname: 'Cornejo',
		position: 'Mitglieder',
	},
	{
		id: '83',
		first_name: 'Alberto ',
		last_name: 'Oyarzun',
		second_surname: 'Scholtbach',
		position: 'Mitglieder',
	},
	{
		id: '84',
		first_name: 'Eduardo',
		last_name: 'Oyarzun',
		second_surname: 'Scholtbach',
		position: 'Mitglieder',
	},
	{
		id: '85',
		first_name: 'Jaime',
		last_name: 'Pavez',
		second_surname: 'Cieselski',
		position: 'Mitglieder',
	},
	{
		id: '86',
		first_name: 'Felipe ',
		last_name: 'Pavez',
		second_surname: 'Von Freeden',
		position: 'Mitglieder',
	},
	{
		id: '87',
		first_name: 'Alex',
		last_name: 'Reuter',
		second_surname: 'Brown',
		position: 'Mitglieder',
	},
	{
		id: '88',
		first_name: 'Willy',
		last_name: 'Reuter',
		second_surname: 'Mauret',
		position: 'Mitglieder',
	},
	{
		id: '89',
		first_name: 'Diego ',
		last_name: 'Reuter',
		second_surname: 'Möenne-Loccoz',
		position: 'Mitglieder',
	},
	{
		id: '90',
		first_name: 'Nicolas ',
		last_name: 'Reuter',
		second_surname: 'Möenne-Loccoz',
		position: 'Mitglieder',
	},
	{
		id: '91',
		first_name: 'Walter',
		last_name: 'Rinsche',
		second_surname: 'Andreu',
		position: 'Mitglieder',
	},
	{
		id: '92',
		first_name: 'Helwin',
		last_name: 'Schmidt',
		second_surname: 'Gebauer',
		position: 'Mitglieder',
	},
	{
		id: '93',
		first_name: 'Rene',
		last_name: 'Schmidt',
		second_surname: 'Gebauer',
		position: 'Mitglieder',
	},
	{
		id: '94',
		first_name: 'Christian',
		last_name: 'Schmidt',
		second_surname: 'Himpel',
		position: 'Mitglieder',
	},
	{
		id: '95',
		first_name: 'Henry',
		last_name: 'Scholtbach',
		second_surname: 'Schuhmacher',
		position: 'Mitglieder',
	},
	{
		id: '96',
		first_name: 'Nelson',
		last_name: 'Schwerter',
		second_surname: 'Siebald',
		position: 'Mitglieder',
	},
	{
		id: '97',
		first_name: 'Doris',
		last_name: 'Stange',
		second_surname: 'Münzenmayer',
		position: 'Mitglieder',
	},
	{
		id: '98',
		first_name: 'Alexa',
		last_name: 'Stange',
		second_surname: 'Paris',
		position: 'Mitglieder',
	},
	{
		id: '99',
		first_name: 'Matias',
		last_name: 'Stange',
		second_surname: 'Paris',
		position: 'Mitglieder',
	},
	{
		id: '100',
		first_name: 'Claudio ',
		last_name: 'Stange',
		second_surname: 'Teske',
		position: 'Mitglieder',
	},
	{
		id: '101',
		first_name: 'Ruby',
		last_name: 'Stange',
		second_surname: 'Wahl',
		position: 'Mitglieder',
	},
	{
		id: '102',
		first_name: 'Yola',
		last_name: 'Stange',
		second_surname: 'Wahl',
		position: 'Mitglieder',
	},
	{
		id: '103',
		first_name: 'Renato',
		last_name: 'Stolzenbach',
		second_surname: 'Minte',
		position: 'Mitglieder',
	},
	{
		id: '104',
		first_name: 'Victor',
		last_name: 'Teuber',
		second_surname: 'Donoso',
		position: 'Mitglieder',
	},
	{
		id: '105',
		first_name: 'Rodolfo',
		last_name: 'Wahl',
		second_surname: 'Böhme',
		position: 'Mitglieder',
	},
	{
		id: '106',
		first_name: 'Georg',
		last_name: 'Wammes',
		second_surname: 'Matvienko-Sikar',
		position: 'Mitglieder',
	},
	{
		id: '107',
		first_name: 'Anton',
		last_name: 'Wammes',
		second_surname: 'Soto',
		position: 'Mitglieder',
	},
	{
		id: '108',
		first_name: 'Gabrielle',
		last_name: 'Wammes',
		second_surname: 'Soto',
		position: 'Mitglieder',
	},
	{
		id: '109',
		first_name: 'Karl',
		last_name: 'Wammes',
		second_surname: 'Soto',
		position: 'Mitglieder',
	},
	{
		id: '110',
		first_name: 'Victor',
		last_name: 'Weitzler',
		second_surname: 'Stange',
		position: 'Mitglieder',
	},
	{
		id: '111',
		first_name: 'Alberto',
		last_name: 'Weitzler',
		second_surname: 'Zarges',
		position: 'Mitglieder',
	},
	{
		id: '112',
		first_name: 'Helmuth',
		last_name: 'Werner',
		second_surname: 'Schröder',
		position: 'Mitglieder',
	},
	{
		id: '113',
		first_name: 'Ruben ',
		last_name: 'Westermaier',
		second_surname: 'Flores',
		position: 'Mitglieder',
	},
	{
		id: '114',
		first_name: 'Pilar',
		last_name: 'Winkler',
		second_surname: 'Ghio',
		position: 'Mitglieder',
	},
	{
		id: '115',
		first_name: 'Walter',
		last_name: 'Winkler',
		second_surname: 'Thomas',
		position: 'Mitglieder',
	},
	{
		id: '116',
		first_name: 'Guillermo',
		last_name: 'Winkler',
		second_surname: 'Werner',
		position: 'Mitglieder',
	},
];
